version: '3.9'
#
services:
#  backend:
#    container_name: backend
#    build:
#      context: ./backend
#      dockerfile: backend.dockerfile
#    ports:
#      - '5000:5000'
#    volumes:
#      - ./backend:/app
#    depends_on:
#      - keycloak-dev
#
#  google:
#    container_name: google
#    build:
#      context: ./google
#      dockerfile: google.dockerfile
#    ports:
#      - '3000:3000'
#    volumes:
#      - type: bind
#        source: ./google
#        target: /app
#    stdin_open: true
#    tty: true
#    depends_on:
#      - backend


  #---INSTALL MYSQL---
  #  docker volume create mysql_volume
  #  docker network create mysql_network
  #  docker run -d --name db_mysql -p 3306:3306 -p 33060:33060 --network mysql_network -v mysql_volume:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=root --restart=always mysql


  #------case 1--------
  # If you don't want to import realm config from json file
  # 1) Use command: start-dev instead of command: start-dev --import-realm
  # 2) And remove the line ./keycloak:/opt/keycloak/data/import from volumes section
  keycloak-dev:
    container_name: keycloak-dev
    image: quay.io/keycloak/keycloak:22.0.1
#    restart: unless-stopped
    ports:
      - "7020:8080"
    networks:
      - mysql_network # same as mysql network.
#    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    command: start-dev --import-realm
    environment:
      # Keycloak Config
      KC_LOG_LEVEL: INFO # FATAL | ERROR | WARN | WARN | INFO | DEBUG | TRACE | ALL | OFF
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # Mysql Config
      KC_DB: mysql # vendor
      KC_DB_URL_HOST: db_mysql # mysql container name
      KC_DB_URL_DATABASE: keycloak_db # db_name (manually create if it doesn't exist)
      KC_DB_URL_PORT: 3306 # container docker port (Not local machine mapped port) (Not required)
      KC_DB_USERNAME: root # db_user
      KC_DB_PASSWORD: root # db_pass
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import # Mapped local keycloak to container import folder. We just need to put our all config file in ./keycloak folder.
      - ./keycloak/themes/:/opt/keycloak/themes

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - mysql_network # same as mysql network.
    volumes:
      - mailhog_volume:/app/data

volumes:
  mailhog_volume:

networks:
  mysql_network:
    external: true