version: '3.9'
#
services:
#  backend:
#    container_name: backend
#    build:
#      context: ./backend
#      dockerfile: backend.dockerfile
#    ports:
#      - '5000:5000'
#    volumes:
#      - ./backend:/app
#    depends_on:
#      - keycloak-dev
#
#  frontend:
#    container_name: frontend
#    build:
#      context: ./frontend
#      dockerfile: frontend.dockerfile
#    ports:
#      - '3000:3000'
#    volumes:
#      - type: bind
#        source: ./frontend
#        target: /app
#    stdin_open: true
#    tty: true
#    depends_on:
#      - backend


  #---INSTALL MYSQL---
  #  docker volume create mysql_volume
  #  docker network create mysql_network
  #  docker run -d --name db_mysql -p 3306:3306 -p 33060:33060 --network mysql_network -v mysql_volume:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=root --restart=always mysql


  keycloak-dev:
    container_name: keycloak-dev
    image: quay.io/keycloak/keycloak:22.0.1
    ports:
      - "7020:8080"
    networks:
      - mysql_network # network must be same with mysql network.
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
#    command: start-dev
#    restart: unless-stopped
    environment:
      # Keycloak Config
      DEBUG: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
#      KEYCLOAK_IMPORT: /tmp/realm-export.json
#      JAVA_OPTS: "-Dkeycloak:import=/tmp/example-realm.json"
#      KEYCLOAK_MIGRATION_STRATEGY: OVERWRITE_EXISTING
      # Mysql Config
      KC_DB: mysql # vendor
      KC_DB_URL_HOST: db_mysql # mysql container name
      KC_DB_URL_DATABASE: keycloak_db # db_name (manually create if it doesn't exist)
      KC_DB_URL_PORT: 3306 # container docker port (Not local machine mapped port) (Not required)
      KC_DB_USERNAME: root # db_user
      KC_DB_PASSWORD: root # db_pass
#    volumes:
#      - ./keycloak/realm-export.json:/tmp/realm-export.json
#    command:
#      - "-b 0.0.0.0"
#      - "-Dkeycloak.migration.action=import"
#      - "-Dkeycloak.migration.provider=singleFile"
#      - "-Dkeycloak.migration.file=/Users/msn/Downloads/realm-export.json"
#      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"



  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailhog_volume:/app/data

volumes:
  mailhog_volume:

networks:
  mysql_network:
    external: true