version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    ports:
      - "5432:5432"

  keycloak:
    build:
      context: .
    environment:
      - "JAVA_OPTS_APPEND=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
      - "8000:8000"

volumes:
  postgresql_data:
    driver: local

