FROM quay.io/keycloak/keycloak:22.0.1

ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin
ENV KC_HOSTNAME=keycloak
ENV KC_DB_DRIVER=mysql
ENV KC_DB_PASSWORD=keycloak
ENV KC_DB_SCHEMA=keycloak
ENV KC_DB_URL_HOST=172.18.0.3
ENV KC_DB_USERNAME=root

CMD ["start-dev"]
